---
title: "Practice_RMarkdown"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Jason West"
date: "5/17/2020"
output: html_document
---

```{r setup, include=FALSE}
## From: https://resources.github.com/whitepapers/github-and-rstudio/
knitr::opts_chunk$set(echo = FALSE)
```

Draft weather data plots

DISCLAIMER: Data have not gone through any QA/QC checks. No warranties are given about data accuracy or completeness

```{r, message = FALSE, warning = FALSE, fig.cap = "Sonora Research Center"}
## Edwards Plateau savanna study
## Weather station data processing
## Sonora Research Station

library(ggplot2)
library(ggpubr) # probably drop this and customize plots - used as a shortcut now
library(data.table)
library(lubridate)
library(plyr)
source('docs/code/readTOA5.R')

# Import data
weather_data <- readTOA5('docs/data/SonoraMetStation_SonorMet_2019_05_18_16_33_52.dat',
                         nlabelline = 4,addFileName = TRUE)
setDT(weather_data)

ggplot(weather_data, aes(x = DateTime, y = AirTC_Avg)) + 
  xlab("Date") +
  ylab("Air temperature (C)") +
  geom_line() +
#  geom_point(size = 3) +
  theme_pubr()

```

